# Books to Scrape - Web Scraping Project

## Objective
The goal of this project is to scrape book information from the Books to Scrape sandbox website using Python.

## Skills Demonstrated
- HTTP Requests
- HTML Parsing using BeautifulSoup
- Data Extraction
- Functions
- Loops
- Data Cleaning with Pandas
- Feature Engineering
- Exporting Data

## Tools Used
- Python
- Requests
- BeautifulSoup
- Pandas

# STEP 1: Import Libraries

In [1]:
# Import the Requests library to send HTTP requests to websites.
import requests

# Import Pandas for data manipulation and analysis
import pandas as pd

# Import BeautifulSoup to parse and extract information from HTML pages.
from bs4 import BeautifulSoup

# Import urljoin to convert relative URLs into complete URLs.
from urllib.parse import urljoin

# STEP 2: Request Website

In [669]:
# Storing the website URL in a variable so it can be reused and retrive its HTML content
url = "https://books.toscrape.com/"

# Display the Http status code to verify that the request was successful
response = requests.get(url)
print(response.status_code)

200

In [670]:
# Verify if the request was successful 
response = requests.get(url)
if response.status_code == 200:
    print("Website downloaded successfully!")
else:
    print(f"Request failed with status code: {response.status_code}")

Website downloaded successfully!

In [540]:
## Confirming by printing it
print(response.text[:1000])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="static/oscar/favicon.

In [541]:
# Detect and apply the correct text encoding to prevent special character issues
response.encoding = response.apparent_encoding

# STEP 3: Parse HTML

In [542]:
# Parse the HTML document using BeautifulSoup to enable easy navigation of the webpage
soup= BeautifulSoup(response.text, "html.parser")
print(soup.title)

<title>
    All products | Books to Scrape - Sandbox
</title>

In [543]:
## Display the webpage Title to confirm that the page loaded correctly
print(soup.title.text)

    All products | Books to Scrape - Sandbox

# STEP 4: Extract Book Information

In [544]:
## Display the HTML structure of the first book to understand where the required information is stored
first_book = soup.find("article")
print(first_book)

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [546]:
## Locate the first book displayed on the homepage
book= first_book.find("h3").find("a")
print(book)
print(book["title"])

<a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a>
A Light in the Attic

In [545]:
## Extract the selling price of the first book
price= first_book.find("p", class_="price_color")
print(price)
print(price.text)

<p class="price_color">£51.77</p>
£51.77

In [547]:
# locate every book displayed on the homepage and count the number of books
books = soup.find_all ("article", class_="product_pod")
print(len(books))

20

In [549]:
print(type(books))

<class 'bs4.element.ResultSet'>

In [550]:
print(books[0])

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [551]:
## Display if the Book(0) is the first book
print(books[0]== first_book)

True

In [552]:
# Displaying the last book on the homepage
print(books[19])

<article class="product_pod">
<div class="image_container">
<a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
<div class="product_price">
<p class="price_color">£45.17</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [554]:
## Using FOR loop to display the books in the first page
for book in books:
    print(book)

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
<div class="product_price">
<p class="price_color">£20.66</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
<div class="product_price">
<p class="price_color">£17.46</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
<div class="product_price">
<p class="price_color">£52.29</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
<div class="product_price">
<p class="price_color">£35.02</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
<div class="product_price">
<p class="price_color">£57.25</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
<div class="product_price">
<p class="price_color">£23.88</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
<div class="product_price">
<p class="price_color">£37.59</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
<div class="product_price">
<p class="price_color">£51.33</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
<article class="product_pod">
<div class="image_container">
<a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
<div class="product_price">
<p class="price_color">£45.17</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

# STEP 5: Build DataSet

In [555]:
## Create an empty list to store information for every scraped book
book_data =[]
for book in books:
    title=book.find("h3").find("a")["title"]
    price=book.find("p", class_="price_color")
    print(title)
    print(price.text)

A Light in the Attic
£51.77
Tipping the Velvet
£53.74
Soumission
£50.10
Sharp Objects
£47.82
Sapiens: A Brief History of Humankind
£54.23
The Requiem Red
£22.65
The Dirty Little Secrets of Getting Your Dream Job
£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
£22.60
The Black Maria
£52.15
Starving Hearts (Triangular Trade Trilogy, #1)
£13.99
Shakespeare's Sonnets
£20.66
Set Me Free
£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
£52.29
Rip it Up and Start Again
£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
£57.25
Olio
£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849
£37.59
Libertarianism for Beginners
£51.33
It's Only the Himalayas
£45.17

In [556]:
## Create a dictionary for each book
book_info = { 
            "Title": title,
            "Price": price.text
}

In [557]:
## Create a dictionary for each book and append it to the list
book_data=[]
for book in books:
    title=book.find("h3").find("a")["title"]
    price=book.find("p", class_="price_color")
    book_info={"Title": title, "Price": price.text}
    
    book_data.append(book_info)
print(len(book_data))

20

In [558]:
## Displaying the first book title and price
print(book_data[0])

{'Title': 'A Light in the Attic', 'Price': '£51.77'}

In [559]:
## Displaying the second book title and price
print(book_data[1])

{'Title': 'Tipping the Velvet', 'Price': '£53.74'}

In [560]:
## Displaying the last book title and price
print(book_data[-1])

{'Title': "It's Only the Himalayas", 'Price': '£45.17'}

In [662]:
# Convert the list of dictionary into a pandas DataFrame
df = pd.DataFrame(book_data)

In [562]:
## Displaying the book DataFrame
df

                                                Title   Price
0                                A Light in the Attic  £51.77
1                                  Tipping the Velvet  £53.74
2                                          Soumission  £50.10
3                                       Sharp Objects  £47.82
4               Sapiens: A Brief History of Humankind  £54.23
5                                     The Requiem Red  £22.65
6   The Dirty Little Secrets of Getting Your Dream...  £33.34
7   The Coming Woman: A Novel Based on the Life of...  £17.93
8   The Boys in the Boat: Nine Americans and Their...  £22.60
9                                     The Black Maria  £52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99
11                              Shakespeare's Sonnets  £20.66
12                                        Set Me Free  £17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29
14                          Rip it Up and Start Again  £35.02
15  Our Band Could Be Your Life: Scenes from the A...  £57.25
16                                               Olio  £23.88
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59
18                       Libertarianism for Beginners  £51.33
19                            It's Only the Himalayas  £45.17

In [568]:
## Display Dataset information, including Column names and data types
print(df.dtypes)

Title    object
Price    object
dtype: object

In [570]:
## Display the first few records to verify that the data was collected correctly
print(df.head())

                                   Title   Price
0                   A Light in the Attic  £51.77
1                     Tipping the Velvet  £53.74
2                             Soumission  £50.10
3                          Sharp Objects  £47.82
4  Sapiens: A Brief History of Humankind  £54.23

In [571]:
## comfirming if the pricr has been converted to float
print(df.dtypes)

Title    object
Price    object
dtype: object

In [572]:
## Updating fpr availability
availability= book.find("p", class_="instock availability").text.strip()
print(availability)

In stock

In [573]:
## Update availabity in the Dictionary
book_info= {"Title": title, 
            "Price": price,
            "Availability": availability}

In [574]:
book_data=[]
for book in books:
    title=book.find("h3").find("a")["title"]
    price=book.find("p", class_="price_color")
    availability= book.find("p", class_="instock availability").text.strip()
    book_info={"Title": title, "Price": price.text}
    
    book_data.append(book_info)
print(len(book_data))

20

In [575]:
## Adding Availabilty to book data
book_data= []
for book in books:
    title= book.find("h3").find("a")["title"]
    price=book.find("p", class_="price_color").text
    availability= book.find("p", class_="instock availability").text.strip()
    book_info={"Title": title, "Price": price, "Availabilty": availability}


    book_data.append(book_info)
print(len(book_data))

20

In [576]:
## confirming if it has been stored
book_data

[{'Title': 'A Light in the Attic',
  'Price': '£51.77',
  'Availabilty': 'In stock'},
 {'Title': 'Tipping the Velvet', 'Price': '£53.74', 'Availabilty': 'In stock'},
 {'Title': 'Soumission', 'Price': '£50.10', 'Availabilty': 'In stock'},
 {'Title': 'Sharp Objects', 'Price': '£47.82', 'Availabilty': 'In stock'},
 {'Title': 'Sapiens: A Brief History of Humankind',
  'Price': '£54.23',
  'Availabilty': 'In stock'},
 {'Title': 'The Requiem Red', 'Price': '£22.65', 'Availabilty': 'In stock'},
 {'Title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Price': '£33.34',
  'Availabilty': 'In stock'},
 {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Price': '£17.93',
  'Availabilty': 'In stock'},
 {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Price': '£22.60',
  'Availabilty': 'In stock'},
 {'Title': 'The Black Maria', 'Price': '£52.15', 'Availabilty': 'In stock'},
 {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'Price': '£13.99',
  'Availabilty': 'In stock'},
 {'Title': "Shakespeare's Sonnets",
  'Price': '£20.66',
  'Availabilty': 'In stock'},
 {'Title': 'Set Me Free', 'Price': '£17.46', 'Availabilty': 'In stock'},
 {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Price': '£52.29',
  'Availabilty': 'In stock'},
 {'Title': 'Rip it Up and Start Again',
  'Price': '£35.02',
  'Availabilty': 'In stock'},
 {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Price': '£57.25',
  'Availabilty': 'In stock'},
 {'Title': 'Olio', 'Price': '£23.88', 'Availabilty': 'In stock'},
 {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Price': '£37.59',
  'Availabilty': 'In stock'},
 {'Title': 'Libertarianism for Beginners',
  'Price': '£51.33',
  'Availabilty': 'In stock'},
 {'Title': "It's Only the Himalayas",
  'Price': '£45.17',
  'Availabilty': 'In stock'}]

In [577]:
## Storing Availabilty
df = pd.DataFrame(book_data)

In [578]:
## checking the Dataframe
df

                                                Title   Price Availabilty
0                                A Light in the Attic  £51.77    In stock
1                                  Tipping the Velvet  £53.74    In stock
2                                          Soumission  £50.10    In stock
3                                       Sharp Objects  £47.82    In stock
4               Sapiens: A Brief History of Humankind  £54.23    In stock
5                                     The Requiem Red  £22.65    In stock
6   The Dirty Little Secrets of Getting Your Dream...  £33.34    In stock
7   The Coming Woman: A Novel Based on the Life of...  £17.93    In stock
8   The Boys in the Boat: Nine Americans and Their...  £22.60    In stock
9                                     The Black Maria  £52.15    In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    In stock
11                              Shakespeare's Sonnets  £20.66    In stock
12                                        Set Me Free  £17.46    In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29    In stock
14                          Rip it Up and Start Again  £35.02    In stock
15  Our Band Could Be Your Life: Scenes from the A...  £57.25    In stock
16                                               Olio  £23.88    In stock
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    In stock
18                       Libertarianism for Beginners  £51.33    In stock
19                            It's Only the Himalayas  £45.17    In stock

In [579]:
## Printing the datatypes
print(df.dtypes)

Title          object
Price          object
Availabilty    object
dtype: object

In [580]:
df

                                                Title   Price Availabilty
0                                A Light in the Attic  £51.77    In stock
1                                  Tipping the Velvet  £53.74    In stock
2                                          Soumission  £50.10    In stock
3                                       Sharp Objects  £47.82    In stock
4               Sapiens: A Brief History of Humankind  £54.23    In stock
5                                     The Requiem Red  £22.65    In stock
6   The Dirty Little Secrets of Getting Your Dream...  £33.34    In stock
7   The Coming Woman: A Novel Based on the Life of...  £17.93    In stock
8   The Boys in the Boat: Nine Americans and Their...  £22.60    In stock
9                                     The Black Maria  £52.15    In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    In stock
11                              Shakespeare's Sonnets  £20.66    In stock
12                                        Set Me Free  £17.46    In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29    In stock
14                          Rip it Up and Start Again  £35.02    In stock
15  Our Band Could Be Your Life: Scenes from the A...  £57.25    In stock
16                                               Olio  £23.88    In stock
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    In stock
18                       Libertarianism for Beginners  £51.33    In stock
19                            It's Only the Himalayas  £45.17    In stock

In [581]:
# cofirming if it changed to float
df["Price"].dtype

dtype('O')

In [582]:
## decribing the data
df["Price"].describe()

count         20
unique        20
top       £51.77
freq           1
Name: Price, dtype: object

### Extracting the Star Ratings

In [583]:
## Inspecting the class fior the first book
rating = books[0].find("p", class_="star-rating")

print(rating)

<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>

In [584]:
## printing the star rating
print(rating["class"])

['star-rating', 'Three']

In [585]:
## Extracting only the the rating number
rating= books[0].find("p", class_="star-rating")["class"][1]
print(rating)

Three

### Adding Ratings to the Dataset

In [586]:
## Creating a mapping Dictionary
rating_map= {
            "One": 1,
            "Two":2,
            "Three":3,
            "Four": 4,
            "Five": 5
            }

In [587]:
## Adding rating to book data
book_data =[]
for book in books:
    title= book.find("h3").find("a")["title"]
    price= book.find("p",class_="price_color").text
    availability= book.find("p", class_= "instock availability").text.strip()

    # Extract the word
    rating = book.find("p", class_= "star-rating")["class"][1]
    rating= rating_map[rating]

    # Convert it to number
    book_info ={
        "Title": title,
        "Price": price,
        "Availability": availability,
        "Rating": rating
    }

    book_data.append(book_info)
print(len(book_data))

20

In [588]:
## Storing Star
df = pd.DataFrame(book_data)

In [589]:
## Cross-checking for correction
print(df.head())

                                   Title   Price Availability  Rating
0                   A Light in the Attic  £51.77     In stock       3
1                     Tipping the Velvet  £53.74     In stock       1
2                             Soumission  £50.10     In stock       1
3                          Sharp Objects  £47.82     In stock       4
4  Sapiens: A Brief History of Humankind  £54.23     In stock       5

In [590]:
## checking the table
(df)

,Title,Price,Availability,Rating
0,A Light in the Attic,£51.77,In stock,3
1,Tipping the Velvet,£53.74,In stock,1
2,Soumission,£50.10,In stock,1
3,Sharp Objects,£47.82,In stock,4
4,Sapiens: A Brief History of Humankind,£54.23,In stock,5
5,The Requiem Red,£22.65,In stock,1
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,In stock,4
7,The Coming Woman: A Novel Based on the Life of...,£17.93,In stock,3
8,The Boys in the Boat: Nine Americans and Their...,£22.60,In stock,4
9,The Black Maria,£52.15,In stock,1
10,"Starving Hearts (Triangular Trade Trilogy, #1)",£13.99,In stock,2
11,Shakespeare's Sonnets,£20.66,In stock,4
12,Set Me Free,£17.46,In stock,5
13,Scott Pilgrim's Precious Little Life (Scott Pi...,£52.29,In stock,5
14,Rip it Up and Start Again,£35.02,In stock,5
15,Our Band Could Be Your Life: Scenes from the A...,£57.25,In stock,3
16,Olio,£23.88,In stock,1
17,Mesaerion: The Best Science Fiction Stories 18...,£37.59,In stock,1
18,Libertarianism for Beginners,£51.33,In stock,2
19,It's Only the Himalayas,£45.17,In stock,2

In [591]:
## Find the link to Each Book
book = books[0]
link = book.find("h3").find("a")["href"]
print(link)

catalogue/a-light-in-the-attic_1000/index.html

In [667]:
## Using Standard Library Designed for URLs
full_link = urljoin(url, link)
print(full_link)

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

In [593]:
## To verify the individual page has been downloaded
response = requests.get(full_link)
response.encoding = response.apparent_encoding
book_soup = BeautifulSoup(response.text, "html.parser")

print(book_soup.title.text)

    A Light in the Attic | Books to Scrape - Sandbox

In [594]:
# Locate the product information table
# containing details such as UPC, tax, and product type
table= book_soup.find("table")

print(table)

<table class="table table-striped">
<tr>
<th>UPC</th><td>a897fe39b1053632</td>
</tr>
<tr>
<th>Product Type</th><td>Books</td>
</tr>
<tr>
<th>Price (excl. tax)</th><td>£51.77</td>
</tr>
<tr>
<th>Price (incl. tax)</th><td>£51.77</td>
</tr>
<tr>
<th>Tax</th><td>£0.00</td>
</tr>
<tr>
<th>Availability</th>
<td>In stock (22 available)</td>
</tr>
<tr>
<th>Number of reviews</th>
<td>0</td>
</tr>
</table>

#### Extracting Data from each Book Page

In [595]:
## Finding all table rows
rows = book_soup.find("table").find_all("tr")

In [596]:
## Getting the number of Rows
print(len(rows))

7

In [597]:
## Checking the first Row
print(rows[0])

<tr>
<th>UPC</th><td>a897fe39b1053632</td>
</tr>

In [598]:
## Checking the Second Row
print(rows[1])

<tr>
<th>Product Type</th><td>Books</td>
</tr>

In [599]:
## Instead of Extracting the whole table, we'll extract just one row since there is a similar pattern
first_row= rows[0]
print(first_row.find("th").text)
print(first_row.find("td").next)

UPC
a897fe39b1053632

In [600]:
## Building the Dictionary Automatically
product_info= {}
for row in rows:
    key =row.find("th").text
    value = row.find("td").text

    product_info[key]= value
product_info

{'UPC': 'a897fe39b1053632',
 'Product Type': 'Books',
 'Price (excl. tax)': '£51.77',
 'Price (incl. tax)': '£51.77',
 'Tax': '£0.00',
 'Availability': 'In stock (22 available)',
 'Number of reviews': '0'}

In [668]:
## instead of writting the same code repeatedly, i'll package it into a reuseable function
## Creating the fuction

def get_book_details(book):
    link =book.find("h3").find("a")["href"]
    full_link= urljoin(url, link)
    
    response = requests.get(full_link)
    response.encoding= response.apparent_encoding
    soup = BeautifulSoup(response.text, "html.parser")
    rows = soup.find("table").find_all("tr")

    product_info ={}

    for row in rows:
        key= row.find("th").text
        value = row.find("td").text
        product_info[key] = value
     # Dictionary containing product information   
    return product_info

In [602]:
## Testing the Functions
details = get_book_details(books[0])
details

{'UPC': 'a897fe39b1053632',
 'Product Type': 'Books',
 'Price (excl. tax)': '£51.77',
 'Price (incl. tax)': '£51.77',
 'Tax': '£0.00',
 'Availability': 'In stock (22 available)',
 'Number of reviews': '0'}

In [603]:
## Combining all the listing-page Data with the Detail-page data
all_books = []
for book in books:

    title= book.find("h3").find("a")["title"]
    price= book.find("p",class_="price_color").text
    availability= book.find("p", class_= "instock availability").text.strip()

    # Extract the word
    rating = book.find("p", class_= "star-rating")["class"][1]
    rating= rating_map[rating]

    details = get_book_details(book)
    # Convert it to number
    book_info ={
        "Title": title,
        "Price": price,
        "Availability": availability,
        "Rating": rating,
        **details}
    all_books.append(book_info)
print(len(all_books))

20

In [604]:
## Storing the Data and then print the top 5
df= pd.DataFrame(all_books)
df.head()

,Title,Price,Availability,Rating,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Number of reviews
0,A Light in the Attic,£51.77,In stock (22 available),3,a897fe39b1053632,Books,£51.77,£51.77,£0.00,0
1,Tipping the Velvet,£53.74,In stock (20 available),1,90fa61229261140a,Books,£53.74,£53.74,£0.00,0
2,Soumission,£50.10,In stock (20 available),1,6957f44c3847a760,Books,£50.10,£50.10,£0.00,0
3,Sharp Objects,£47.82,In stock (20 available),4,e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,0
4,Sapiens: A Brief History of Humankind,£54.23,In stock (20 available),5,4165285e1663650f,Books,£54.23,£54.23,£0.00,0

# Step 6: Data Cleaning

In [605]:
## Checking the Data types
df.dtypes

Title                object
Price                object
Availability         object
Rating                int64
UPC                  object
Product Type         object
Price (excl. tax)    object
Price (incl. tax)    object
Tax                  object
Number of reviews    object
dtype: object

In [606]:
## getting info about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              20 non-null     object
 1   Price              20 non-null     object
 2   Availability       20 non-null     object
 3   Rating             20 non-null     int64
 4   UPC                20 non-null     object
 5   Product Type       20 non-null     object
 6   Price (excl. tax)  20 non-null     object
 7   Price (incl. tax)  20 non-null     object
 8   Tax                20 non-null     object
 9   Number of reviews  20 non-null     object
dtypes: int64(1), object(9)
memory usage: 1.7+ KB

In [607]:
## Inpecting the dataset clearly
df.describe(include="all")

,Title,Price,Availability,Rating,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Number of reviews
count,20,20,20,20.000000,20,20,20,20,20,20
unique,20,20,3,NaN,20,1,20,20,1,1
top,A Light in the Attic,£51.77,In stock (19 available),NaN,a897fe39b1053632,Books,£51.77,£51.77,£0.00,0
freq,1,1,15,NaN,1,20,1,1,20,20
mean,NaN,NaN,NaN,2.850000,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.565248,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [608]:
## Changing the Price Column to Number from object
df["Price"] = (
    df["Price"]
      .str.replace("£", "", regex=False)
      .astype(float)
)

In [609]:
df["Price"].head()

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: Price, dtype: float64

In [610]:
print(df["Price"].dtype)

float64

In [673]:
## Confirming the detail
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     object
 1   Price         20 non-null     object
 2   Availability  20 non-null     object
 3   Rating        20 non-null     int64
dtypes: int64(1), object(3)
memory usage: 772.0+ bytes

In [674]:
## Checking the Table
df.head()

                                   Title   Price Availability  Rating
0                   A Light in the Attic  £51.77     In stock       3
1                     Tipping the Velvet  £53.74     In stock       1
2                             Soumission  £50.10     In stock       1
3                          Sharp Objects  £47.82     In stock       4
4  Sapiens: A Brief History of Humankind  £54.23     In stock       5

In [612]:
## CLeaning the Availability Column
df["Availability"].iloc[0]

'In stock (22 available)'

In [613]:
## Extracting the Availabilty Column into two Different pieces, i.e Stock Status and Quantity Available
##The text we would like to separate
text= "In Stock (22 available)"
text.split()

['In', 'Stock', '(22', 'available)']

In [614]:
## Separating the third element
text = "In stock (22 available)"

parts = text.split()

quantity = parts[2].replace("(", "")

print(quantity)

22

In [615]:
## Converting the Number(third element) Text to String
quantity= int(parts[2].replace("(", ""))
print(quantity)
print(type(quantity))

22
<class 'int'>

In [617]:
## Updating the Dataset by Separating the Availabity Contens
df["Availability"].str.split().head()

0    [In, stock, (22, available)]
1    [In, stock, (20, available)]
2    [In, stock, (20, available)]
3    [In, stock, (20, available)]
4    [In, stock, (20, available)]
Name: Availability, dtype: object

In [656]:
## Create Stock Status from Availability
## Checking the position of the In
df["Availability"].str.split().str[0]

0     In
1     In
2     In
3     In
4     In
5     In
6     In
7     In
8     In
9     In
10    In
11    In
12    In
13    In
14    In
15    In
16    In
17    In
18    In
19    In
Name: Availability, dtype: object

In [655]:
## Checking the position of the Stock
df["Availability"].str.split().str[1]

0     stock
1     stock
2     stock
3     stock
4     stock
5     stock
6     stock
7     stock
8     stock
9     stock
10    stock
11    stock
12    stock
13    stock
14    stock
15    stock
16    stock
17    stock
18    stock
19    stock
Name: Availability, dtype: object

In [641]:
## Updating the DataFrame
df["Stock_Status"] =df["Availability"].str.split().str[0] + " " + df["Availability"].str.split().str[1]

In [657]:
## Cofiming if the update has reflected to the DataFrame
df.head()

,Title,Price,Availability,Rating,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Number of reviews,Stock_Status,Quantity_Available
0,A Light in the Attic,51.77,In stock (22 available),3,a897fe39b1053632,Books,£51.77,£51.77,£0.00,0,In stock,22
1,Tipping the Velvet,53.74,In stock (20 available),1,90fa61229261140a,Books,£53.74,£53.74,£0.00,0,In stock,20
2,Soumission,50.10,In stock (20 available),1,6957f44c3847a760,Books,£50.10,£50.10,£0.00,0,In stock,20
3,Sharp Objects,47.82,In stock (20 available),4,e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,0,In stock,20
4,Sapiens: A Brief History of Humankind,54.23,In stock (20 available),5,4165285e1663650f,Books,£54.23,£54.23,£0.00,0,In stock,20

In [646]:
## Create quantity Available Column from Availability
parts= df["Availability"].str.split()
quantity= parts.str[2]
quantity = parts.str[2].str.replace("(", "", regex=False).astype(int)
df["Quantity_Available"]= quantity

In [653]:
## Checking the Table if it has been updated
quantity

0     22
1     20
2     20
3     20
4     20
5     19
6     19
7     19
8     19
9     19
10    19
11    19
12    19
13    19
14    19
15    19
16    19
17    19
18    19
19    19
Name: Availability, dtype: int64

In [650]:
df["Quantity_Available"] = (
    df["Availability"]
      .str.split()
      .str[2]
      .str.replace("(", "", regex=False)
      .astype(int)
)

In [654]:
## Checking if the quantity has been added to the Table
df

,Title,Price,Availability,Rating,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Number of reviews,Stock_Status,Quantity_Available
0,A Light in the Attic,51.77,In stock (22 available),3,a897fe39b1053632,Books,£51.77,£51.77,£0.00,0,In stock,22
1,Tipping the Velvet,53.74,In stock (20 available),1,90fa61229261140a,Books,£53.74,£53.74,£0.00,0,In stock,20
2,Soumission,50.10,In stock (20 available),1,6957f44c3847a760,Books,£50.10,£50.10,£0.00,0,In stock,20
3,Sharp Objects,47.82,In stock (20 available),4,e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,0,In stock,20
4,Sapiens: A Brief History of Humankind,54.23,In stock (20 available),5,4165285e1663650f,Books,£54.23,£54.23,£0.00,0,In stock,20
5,The Requiem Red,22.65,In stock (19 available),1,f77dbf2323deb740,Books,£22.65,£22.65,£0.00,0,In stock,19
6,The Dirty Little Secrets of Getting Your Dream...,33.34,In stock (19 available),4,2597b5a345f45e1b,Books,£33.34,£33.34,£0.00,0,In stock,19
7,The Coming Woman: A Novel Based on the Life of...,17.93,In stock (19 available),3,e72a5dfc7e9267b2,Books,£17.93,£17.93,£0.00,0,In stock,19
8,The Boys in the Boat: Nine Americans and Their...,22.60,In stock (19 available),4,e10e1e165dc8be4a,Books,£22.60,£22.60,£0.00,0,In stock,19
9,The Black Maria,52.15,In stock (19 available),1,1dfe412b8ac00530,Books,£52.15,£52.15,£0.00,0,In stock,19
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,In stock (19 available),2,0312262ecafa5a40,Books,£13.99,£13.99,£0.00,0,In stock,19
11,Shakespeare's Sonnets,20.66,In stock (19 available),4,30a7f60cd76ca58c,Books,£20.66,£20.66,£0.00,0,In stock,19
12,Set Me Free,17.46,In stock (19 available),5,ce6396b0f23f6ecc,Books,£17.46,£17.46,£0.00,0,In stock,19
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock (19 available),5,3b1c02bac2a429e6,Books,£52.29,£52.29,£0.00,0,In stock,19
14,Rip it Up and Start Again,35.02,In stock (19 available),5,a34ba96d4081e6a4,Books,£35.02,£35.02,£0.00,0,In stock,19
15,Our Band Could Be Your Life: Scenes from the A...,57.25,In stock (19 available),3,deda3e61b9514b83,Books,£57.25,£57.25,£0.00,0,In stock,19
16,Olio,23.88,In stock (19 available),1,feb7cc7701ecf901,Books,£23.88,£23.88,£0.00,0,In stock,19
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,In stock (19 available),1,e30f54cea9b38190,Books,£37.59,£37.59,£0.00,0,In stock,19
18,Libertarianism for Beginners,51.33,In stock (19 available),2,a18a4f574854aced,Books,£51.33,£51.33,£0.00,0,In stock,19
19,It's Only the Himalayas,45.17,In stock (19 available),2,a22124811bfa8350,Books,£45.17,£45.17,£0.00,0,In stock,19

# STEP 7: Exporting the Data

In [675]:
## Saving the Cleaned Dataset
df.to_csv ("books=csv", index=False)
print("Dataset exported successfully!")

Dataset exported successfully!

In [660]:
## Verifying it by reading it back
pd.read_csv("books=csv")

,Title,Price,Availability,Rating,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Number of reviews,Stock_Status,Quantity_Available
0,A Light in the Attic,51.77,In stock (22 available),3,a897fe39b1053632,Books,£51.77,£51.77,£0.00,0,In stock,22
1,Tipping the Velvet,53.74,In stock (20 available),1,90fa61229261140a,Books,£53.74,£53.74,£0.00,0,In stock,20
2,Soumission,50.10,In stock (20 available),1,6957f44c3847a760,Books,£50.10,£50.10,£0.00,0,In stock,20
3,Sharp Objects,47.82,In stock (20 available),4,e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,0,In stock,20
4,Sapiens: A Brief History of Humankind,54.23,In stock (20 available),5,4165285e1663650f,Books,£54.23,£54.23,£0.00,0,In stock,20
5,The Requiem Red,22.65,In stock (19 available),1,f77dbf2323deb740,Books,£22.65,£22.65,£0.00,0,In stock,19
6,The Dirty Little Secrets of Getting Your Dream...,33.34,In stock (19 available),4,2597b5a345f45e1b,Books,£33.34,£33.34,£0.00,0,In stock,19
7,The Coming Woman: A Novel Based on the Life of...,17.93,In stock (19 available),3,e72a5dfc7e9267b2,Books,£17.93,£17.93,£0.00,0,In stock,19
8,The Boys in the Boat: Nine Americans and Their...,22.60,In stock (19 available),4,e10e1e165dc8be4a,Books,£22.60,£22.60,£0.00,0,In stock,19
9,The Black Maria,52.15,In stock (19 available),1,1dfe412b8ac00530,Books,£52.15,£52.15,£0.00,0,In stock,19
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,In stock (19 available),2,0312262ecafa5a40,Books,£13.99,£13.99,£0.00,0,In stock,19
11,Shakespeare's Sonnets,20.66,In stock (19 available),4,30a7f60cd76ca58c,Books,£20.66,£20.66,£0.00,0,In stock,19
12,Set Me Free,17.46,In stock (19 available),5,ce6396b0f23f6ecc,Books,£17.46,£17.46,£0.00,0,In stock,19
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock (19 available),5,3b1c02bac2a429e6,Books,£52.29,£52.29,£0.00,0,In stock,19
14,Rip it Up and Start Again,35.02,In stock (19 available),5,a34ba96d4081e6a4,Books,£35.02,£35.02,£0.00,0,In stock,19
15,Our Band Could Be Your Life: Scenes from the A...,57.25,In stock (19 available),3,deda3e61b9514b83,Books,£57.25,£57.25,£0.00,0,In stock,19
16,Olio,23.88,In stock (19 available),1,feb7cc7701ecf901,Books,£23.88,£23.88,£0.00,0,In stock,19
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,In stock (19 available),1,e30f54cea9b38190,Books,£37.59,£37.59,£0.00,0,In stock,19
18,Libertarianism for Beginners,51.33,In stock (19 available),2,a18a4f574854aced,Books,£51.33,£51.33,£0.00,0,In stock,19
19,It's Only the Himalayas,45.17,In stock (19 available),2,a22124811bfa8350,Books,£45.17,£45.17,£0.00,0,In stock,19

# Project Summary

This project successfully scraped information from the Books to Scrape sandbox website.

The dataset contains:

- Book Title
- Price
- Rating
- Availability
- Quantity Available
- Product Type
- UPC
- Tax
- Number of Reviews

The data was cleaned and exported as a CSV file for further analysis.